#!/usr/bin/env node
const yargs = require('yargs')
const Commands = require('./commands/attributes')
const Actions = require('./commands/actions')
const Api = require('./commands/api')
const Application = require('./commands/application')

yargs
  .command('play', 'play music', () => {
    Actions.play()
    Commands.getStatus()
   })
  .command('pause', 'pause music', () => {
    Actions.pause()
    Commands.getStatus()
   })
   .command('next', 'next music', () => {
    Actions.next()
    Commands.getStatus()
   })
  .command('prev', 'previous music', () => {
    Actions.previous()
    Commands.getStatus()
   })
  .command('search [song]', 'search song', () => {
    console.log('not available yet - wip')
    return
    Api.findSong(argv.song, function(error, stdout, stderr) {
      if (error) {console.log(error); return;}
      Actions.playTrack(stdout.trim())
      Commands.getStatus()
    })
  })
  .command('status', 'status music', () => {
    Commands.getStatus()
  })
  .command('open', 'status music', () => {
    Application.open()
  })
  .command('close', 'status music', () => {
    Application.close()
  })
  .argv
